# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: zaheer.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zaheer.io" # the base hostname & protocol for your site, e.g. http://example.com

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/logo-square-300.jpeg"
      background_image: "samuel-austin-77663-unsplash.jpg"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss

# PurgeCSS
css_dir: "assets/"

# SEO
twitter:
  username: zaheerbaloch
  card: summary

social:
  name: Zaher Baloch
  links:
    - https://twitter.com/zaheerbaloch
    - https://github.com/zbaloch

author:
  twitter: zaheerbaloch

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - netlify.toml
  - .gitignore
  - statickit.json
